name: app_install_date
description: This plugin helps you to get install date of the application
version: 0.1.5
homepage: https://github.com/Maksimka101/app_install_date

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.13

dev_dependencies:
  flutter_lints: ">=2.0.1 <5.0.0"
  flutter_test:
    sdk: flutter
  lints: ">=1.0.1 <5.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.zemlyanikinmaksim.app_install_date
        pluginClass: AppInstallDatePlugin
      ios:
        pluginClass: AppInstallDatePlugin
      macos:
        pluginClass: AppInstallDatePlugin
